### ISSUE TITLE
mvn not executable on jruby-9.0.0.0.rc2

### ISSUE THREAD

**Issue by blankenshipz** [jruby/docker-jruby#10]
FYI

Just in case anyone runs into this problem - there's a known issue upstream in `jruby-9.0.0.0.rc2` where the `mvn` binary at `lib/ruby/maven-home/bin/mvn` is not executable. 

Here's the issue: https://github.com/jruby/jruby/issues/3134
The fix on master: https://github.com/jruby/jruby/commit/d451c159bb6ead123f6a647f6c5d3172c9e9c028

**Comment by cpuguy83** [comment]
Closing as this looks resolved now.
