### ISSUE TITLE
Create github releases after every release

### ISSUE THREAD

**Issue by elgalu** [jruby/docker-jruby#17]
Hi, thanks for this image, could you create [releases](https://github.com/cpuguy83/docker-jruby/releases) so we get notified as watchers?

**Comment by cpuguy83** [comment]
This can be tracked on DockerHub, it is the official jruby image.
https://hub.docker.com/_/jruby/

In your own images you can receive notifications (or trigger an automatic rebuild, whatever) when the official image is pushed.

**Comment by elgalu** [comment]
Maybe I'm missing something but:

Option 1: I need to manually check that page

Option 2: I don't own this jruby image and I don't want to trigger automatic builds, just want to know by email when a new release of this image is pushed. Can't find where to subscribe at https://hub.docker.com/_/jruby/ as a non-owner.

**Comment by cpuguy83** [comment]
Ok, I created a release for 9.1.7 back through 9.1.5.

Thanks!
