### ISSUE TITLE
Add Git to the base image to support gems from Git sources

### ISSUE THREAD

**Issue by chriskilding** [jruby/docker-jruby#2]
If I have any gems which are coming from Git repositories, such that my Gemfile looks something like this:

```
source 'https://rubygems.org'

# Some regular gems
gem "bson", "~> 2.2.1"
gem 'mongoid', '~> 4.0.0'
gem "puma", '~> 2.9.0'

# A gem from a Git source
gem 'status-reporter', github: 'themasterchef/status-reporter', require: 'status_reporter'
```

The onbuild image will bomb out at the `bundle install` trigger, because Git is not installed on the base image:

```
Fetching source index from https://rubygems.org/
You need to install git to be able to use gems from git repositories. For help
installing git, please refer to GitHub's tutorial at
https://help.github.com/articles/set-up-git
<Exit with error>
```

 Please could you add Git to the base image for onbuild to support gems from non-rubygems sources. Basically just ensure that the following line runs before 'bundle install' does (maybe you don't need the apt-get update first):

```
RUN apt-get update && apt-get -y install git
```

**Comment by cpuguy83** [comment]
Yep, I'll look into this for onbuild specifically.

**Comment by cpuguy83** [comment]
This is resolved.
It may take a little bit for the image to be pushed to Docker Hub.
