### ISSUE TITLE
Question: When do new versions appear on hub.docker.com?

### ISSUE THREAD

**Issue by ylansegal** [jruby/docker-jruby#23]
Master currently already has jruby-9.1.4.0, but I can't see it in https://hub.docker.com/r/library/jruby/ yet. How and when does that version appear in hub.docker.com? 

Thanks for maintaining this image 👍

**Comment by cpuguy83** [comment]
See https://github.com/docker-library/official-images/pull/2114

It'll likely be a couple of hours after that PR is merged.

**Comment by ylansegal** [comment]
Thanks... I'll follow along there.
