### ISSUE TITLE
jruby:9.1.3-alpine image is jruby 9.1.2.0

### ISSUE THREAD

**Issue by shakiyam** [jruby/docker-jruby#24]
```
$ docker run --rm -it jruby:9.1.3-alpine jruby -v
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f OpenJDK 64-Bit Server VM 25.92-b14 on 1.8.0_92-internal-alpine-r1-b14 +jit [linux-x86_64]
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
jruby               9-alpine            534f74c0c1c8        5 days ago          162.1 MB
jruby               9.1.3-alpine        534f74c0c1c8        5 days ago          162.1 MB
```

**Comment by cpuguy83** [comment]
ping @tianon

**Comment by tianon** [comment]
Huh, this is definitely an odd one -- I looked through the PR history over on https://github.com/docker-library/official-images, and all the Git diffs look correct (I don't see anything that could've caused this), and I just tested the current version (9.1.8) and it does not suffer from this issue. :disappointed:

I think there must have been an issue with our build/push process that somehow got the older 9.1.2 image pushed at the 9.1.3 tag; sorry about that!  Is 9.1.3 important enough that I should do some archaeological digging to restore the previous contents, or do you think we're safe enough to let this one slide and just keep an eye out for repeat occurrences?

**Comment by cpuguy83** [comment]
It's probably not important, just a patch release.

@shakiyam ?

**Comment by shakiyam** [comment]
I agree with you, it is not important. I hope the build / push process is improved and the same mistakes are not repeated.
