### ISSUE TITLE
JRuby 9.1.4.0 missing from hub.docker.com

### ISSUE THREAD

**Issue by ivoanjo** [jruby/docker-jruby#25]
It seems that while this repository was updated with JRuby 9.1.4.0, the release was not uploaded to https://hub.docker.com/_/jruby/.

Could you kindly make it available there?

Thanks for your awesome work, as always :bow: :smile: :tada: !

**Comment by cpuguy83** [comment]
It will be available shortly after https://github.com/docker-library/official-images/pull/2114 is merged
Thanks!
