### ISSUE TITLE
ppc64le dockerhub images

### ISSUE THREAD

**Issue by vaibhavsood** [jruby/docker-jruby#32]
Hi, I'm looking to enable docker containers for packages like jruby for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum.

The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, as mentioned there they recommend having a single dockerfile with swithches for arch-specific changes, want to understand if ppc64le additions would be accepted to the dockerfile here (can raise a PR) and if the ppc64le image creation process can be initiated subsequently under docker-library/official-images (would mostly need changes to the metadata file https://github.com/docker-library/official-images/blob/master/library/jruby)

Thanks!

**Comment by cpuguy83** [comment]
Thanks!

I've added arch's for everything supported by the openjdk image.
https://github.com/docker-library/official-images/pull/3633
