### ISSUE TITLE
Support 9.1 and 9.2 but drop support for 1.7

### ISSUE THREAD

**Issue by deivid-rodriguez** [jruby/docker-jruby#35]
I haven't found an official maintainance policy for jruby, but I'm pretty certain 1.7 has already been EOL'd, whereas 9.1 is still maintained. The reason why I think that is that jruby 1.7 is MRI 1.9.3 compatible (which was EOL'd a long time ago), whereas jruby 9.1 is MRI 2.3 compatible (which is still supported).

I raise this issue because I want to test my library against all official jrubies, but I can only find 9.2 on https://github.com/docker-library/official-images/blob/master/library/jruby.

Thanks! :+1:

**Comment by cpuguy83** [comment]
9.1 images are available:

```
$ docker pull jruby:9.1
9.1: Pulling from library/jruby
cc1a78bfd46b: Pull complete
6861473222a6: Pull complete
7e0b9c3b5ae0: Pull complete
ae14ee39877a: Pull complete
8085c1b536f0: Pull complete
6e1431e84c0c: Pull complete
ca0e3df5a1fd: Pull complete
d2cb611ced6c: Pull complete
1661e08dd59f: Pull complete
968ab4a9a40a: Pull complete
88364f9495d1: Pull complete
357dda7be20a: Pull complete
d371513b9205: Pull complete
Digest: sha256:78197feb5c21e44f19d254f40942f3ce437d143ca28b8116ba5b0660af455c2f
Status: Downloaded newer image for jruby:9.1

$ docker pull jruby:9.1.17.0
9.1.17.0: Pulling from library/jruby
Digest: sha256:78197feb5c21e44f19d254f40942f3ce437d143ca28b8116ba5b0660af455c2f
Status: Downloaded newer image for jruby:9.1.17.0
```

**Comment by deivid-rodriguez** [comment]
Interesting, I thought they were not because they were not listed in https://hub.docker.com/_/jruby/ nor https://github.com/docker-library/official-images/blob/master/library/jruby. Are they available but not official or something like that?

My problem is that circleci uses https://github.com/docker-library/official-images/blob/master/library/jruby as a manifest to decide which official libraries to build its additions on top of.

**Comment by cpuguy83** [comment]
Hmm... we can probably still list them to make sure they are rebuilt when security issues arise in lower layers.

**Comment by cpuguy83** [comment]
They are official just not actively built.

**Comment by cpuguy83** [comment]
https://github.com/docker-library/official-images/pull/4971

**Comment by deivid-rodriguez** [comment]
Thanks so much @cpuguy83! :heart:
