### ISSUE TITLE
jruby:9.1.17.0-alpine is a Debian

### ISSUE THREAD

**Issue by jpsikorra** [jruby/docker-jruby#36]
`Digest: sha256:13edf51fa3f6646915a17a3fe942e42b64dc217da537666a1014c804c7ea98c8`

```
docker run --rm jruby:9.1.17.0-alpine cat /etc/issue
-> Debian GNU/Linux 9 \n \l
```

**Comment by cpuguy83** [comment]
:(

Fixing here: https://github.com/docker-library/official-images/pull/4979

**Comment by cpuguy83** [comment]
Fixed in upstream, this should get rebuilt and pushed soon.

Thanks!
