### ISSUE TITLE
Use bundler --jobs to speedup gem installation?

### ISSUE THREAD

**Issue by nightscape** [jruby/docker-jruby#4]
Hi @cpuguy83,

bundler has a nice option `--jobs NUM_WORKERS` to speed up gem installation.
What do you think of adding that to the `ONBUILD RUN bundle install` line?

Best
  Martin

**Comment by cpuguy83** [comment]
I'd like to keep this as close to the main ruby image as possible.

ping @tianon @yosifkit

**Comment by tianon** [comment]
docker-library/ruby#35 would be the relevant issue for `ruby` :+1:

**Comment by cpuguy83** [comment]
Since `ONBUILD` is deprecated in the official images, I'm going to close this as not neccessary.
Thanks!
