### ISSUE TITLE
Is jruby:9.2.5.1 wrong version tag?

### ISSUE THREAD

**Issue by fukayatsu** [jruby/docker-jruby#40]
> [Home — JRuby.org](https://www.jruby.org/)
> Latest release - 9.2.5.0

It seems JRuby 9.2.5.1 is not yet released at this point.
`jruby:9.2.5.1` should be `jruby:9.2.5.0` ?

```
$ docker run --rm -it jruby:9.2.5.1

irb> JRUBY_VERSION
=> "9.2.5.0"
```

```
$ docker run --rm -it jruby:9.2.5.0

docker: Error response from daemon: manifest for jruby:9.2.5.0 not found.
```

**Comment by cpuguy83** [comment]
😞 PR to fix it is here: https://github.com/docker-library/official-images/pull/5186

**Comment by cpuguy83** [comment]
This is fixed.
