### ISSUE TITLE
JRuby automated builds fail with: NotImplementedError: flock unsupported or native support failed to load

### ISSUE THREAD

**Issue by zacburns** [jruby/docker-jruby#42]
Fetching: bundler-2.0.1.gem (100%)
NotImplementedError: flock unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
                   flock at org/jruby/RubyFile.java:317
            write_binary at /opt/jruby/lib/ruby/stdlib/rubygems.rb:897
                    open at org/jruby/RubyIO.java:1154
                    open at org/jruby/RubyKernel.java:317
            write_binary at /opt/jruby/lib/ruby/stdlib/rubygems.rb:895
       cache_update_path at /opt/jruby/lib/ruby/stdlib/rubygems/remote_fetcher.rb:334
                download at /opt/jruby/lib/ruby/stdlib/rubygems/remote_fetcher.rb:188
                download at /opt/jruby/lib/ruby/stdlib/rubygems/source.rb:215
                 install at /opt/jruby/lib/ruby/stdlib/rubygems/resolver/specification.rb:91
                 install at /opt/jruby/lib/ruby/stdlib/rubygems/request_set.rb:168
                    each at org/jruby/RubyArray.java:1792
                 install at /opt/jruby/lib/ruby/stdlib/rubygems/request_set.rb:156
             install_gem at /opt/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:205
            install_gems at /opt/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:255
                    each at org/jruby/RubyArray.java:1792
            install_gems at /opt/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:251
                 execute at /opt/jruby/lib/ruby/stdlib/rubygems/commands/install_command.rb:158
  invoke_with_build_args at /opt/jruby/lib/ruby/stdlib/rubygems/command.rb:313
            process_args at /opt/jruby/lib/ruby/stdlib/rubygems/command_manager.rb:171
                     run at /opt/jruby/lib/ruby/stdlib/rubygems/command_manager.rb:141
                     run at /opt/jruby/lib/ruby/stdlib/rubygems/gem_runner.rb:59
                  <main> at /opt/jruby/bin/jgem:21
                    load at org/jruby/RubyKernel.java:1007
                  <main> at /opt/jruby/bin/gem:4
[0mRemoving intermediate container 0af2cfff5bfb
The command '/bin/sh -c gem install bundler rake net-telnet xmlrpc' returned a non-zero code: 1

**Comment by cpuguy83** [comment]
What version of the image... can you provide the full image name you are using?

**Comment by zacburns** [comment]
The s390x version with build results here: https://doi-janky.infosiftr.net/job/multiarch/job/s390x/job/jruby/
I'm not using a specific image just yet because `docker pull s390x/jruby` fails. It appears that maybe the pipeline has never created a working image?

**Comment by cpuguy83** [comment]
Only x86 is support these days due to changes in the java base images.
