### ISSUE TITLE
Support 9.2.6.0

### ISSUE THREAD

**Issue by olleolleolle** [jruby/docker-jruby#44]
This Issue is about the new version of JRuby, 9.2.6.0

Inspiration: This issue has sha512 values - https://github.com/rvm/rvm/pull/4614

**Comment by cpuguy83** [comment]
Thanks.
I am currently in the hospital for a minor surgery. Can you make a PR and I can merge?
From there will need to update the docker-library/official-images repo.

**Comment by cpuguy83** [comment]
To update, just update the version in 9000/VERSION and run update.sh

**Comment by olleolleolle** [comment]
Here's hoping for a speedy recovery.

The PR's submitted. **Update**: Merged!

**Comment by cpuguy83** [comment]
official-images just merged.
Thanks!

**Comment by olleolleolle** [comment]
Great to see you back! Hope all went well.

**Comment by cpuguy83** [comment]
Thanks! So far so good.
