### ISSUE TITLE
Docker Hub page shows 1 version incorrectly

### ISSUE THREAD

**Issue by olleolleolle** [jruby/docker-jruby#47]
![image](https://user-images.githubusercontent.com/211/52843809-74750600-3103-11e9-9d5b-83ed41b566e4.png)

The first row, it has one of the version aliases listed as 9.2.**5**.

**Comment by cpuguy83** [comment]
Dang, thanks!
Fixing in https://github.com/docker-library/official-images/pull/5449

**Comment by cpuguy83** [comment]
Merged.
