### ISSUE TITLE
Support different JDK/JRE versions within the JRuby versions

### ISSUE THREAD

**Issue by v1v** [jruby/docker-jruby#50]
Hi there,

Just wanted to know whether there are any reasons why the JRuby docker images don't support other JDK/JRE versions such as `11`, `12` and `13`. In other words, I'd like to use `jruby` with the below versions:
- `jruby:9.1-7-jdk`
- `jruby:9.1-8-jdk`
- `jruby:9.1-11-jdk`
- `jruby:9.2-12-jdk`
- `jruby:9.2-13-jdk`

And also with different flavors such as `alpine` and `jre`

What do you think? Is that something you might consider to be done within this docker images?

I'm happy to provide a PR to support this particular use case, which I managed to implement it like a draft:
- https://github.com/v1v/docker-jruby/tree/versions

Thanks

**Comment by cpuguy83** [comment]
Only reason is:

1. Figuring out a proper naming scheme for the official images
2. Actually doing the work

Note that I've reached out to the jruby team to take over this work.
https://github.com/jruby/jruby/issues/5598

**Comment by v1v** [comment]
Got it! Thanks for the answer. I'll keep an eye in the reference ticket and see whether I could help with the implementation side. Thanks again

**Comment by tianon** [comment]
I think accounting for https://github.com/docker-library/openjdk/pull/322 is probably relevant with this work, and it's possible the naming scheme used within `tomcat` (that accounts for new `adoptopenjdk`-based variants) could be of interest: https://github.com/docker-library/tomcat/pull/160

**Comment by cpuguy83** [comment]
Added support for jdk/jre11, jdk 14, and jdk 15.
PR to update the official image is here: https://github.com/docker-library/official-images/pull/7974
