### ISSUE TITLE
Push docker image with tag 9.2.8.0-jre-alpine

### ISSUE THREAD

**Issue by mrnonz** [jruby/docker-jruby#54]
Hi, I want you to push new docker image with tag `9.2.8.0-jre-alpine`  to https://hub.docker.com/_/jruby

thank you

**Comment by onyxraven** [comment]
It does look like both the alpine (jre and jdk) images got missed for 9.2.8 - was this on purpose (or theres an error)? It looks like the update.sh should have still built and pushed those. 

@cpuguy83

**Comment by cpuguy83** [comment]
Yes it looks like there was an issue with update.sh being run with BSD sed instead of gnu sed. :(

**Comment by cpuguy83** [comment]
Closing since alpine is no longer supported in the java base.
