### ISSUE TITLE
Will this no longer hold official Alpine based images?

### ISSUE THREAD

**Issue by albertogg** [jruby/docker-jruby#56]
Hi @cpuguy83, hope you are doing well, quick question, I don't understand why the alpine based images were removed from the oficial docker registry see: https://github.com/docker-library/official-images/commit/bd7798d5cf20ffa9d07b0c3a002e43d3773bbd04#diff-18ff5d1813ddc2309b707bc3d7a2962f

Was this intentional? It seems that #54 is related.

Thanks

**Comment by cpuguy83** [comment]
As I understand it, alpine images are no longer available for openjdk.
https://github.com/docker-library/openjdk/pull/322

**Comment by albertogg** [comment]
Thanks @cpuguy83, I was not aware of this, just checked and you are correct. We will move on to the stretch based version.

Thanks again!
