### ISSUE TITLE
[Tag Request] Support Debian Stretch and Buster tag

### ISSUE THREAD

**Issue by LizhangX** [jruby/docker-jruby#58]
The base image of jruby from openjdk 8 is updated to Debian 10 buster.
Due to this [commit](https://github.com/docker-library/openjdk/commit/75b0f85e10c8cafa4fcdbbeea578a0adf99f657a
) for openjdk8 docker image 6 days ago.

If we try to do apt-get install any openjdk 8 related packages with jruby base, there is none since Debian drop support for openjdk 8.

Maybe in the jruby image, we can also have the stretch and buster tag to support 8-jdk-buster, 8-jdk-stretch( likewise for jre and alpine).

Or if there is any better solution that is also welcome.

Thank you.

**Comment by cpuguy83** [comment]
There is no stretch equivalent that is currently supported upstream (in the openjdk image), as such we cannot support that here.

**Comment by LizhangX** [comment]
I see they have the stretch image eg. for jdk: [openjdk:8-jdk-stretch](https://hub.docker.com/_/openjdk?tab=tags&page=1&name=8-jdk-stretch).

As now the openjdk8 using [here](https://github.com/cpuguy83/docker-jruby/blob/4f090791f66566bb1954b0d124f109505e748fc5/9000/jdk/Dockerfile#L1) is the buster equivalent since 6 days ago.

**Comment by cpuguy83** [comment]
That is true, but stretch is no longer being built.

Here is the manifest for the openjdk build:
https://github.com/docker-library/official-images/blob/master/library/openjdk

Only the tags in that manifest are actively built.

**Comment by LizhangX** [comment]
Gotcha, make sense. 
Thank you very much for the clarification!

May I ask will there be a java 11 support plan for jruby docker in the near future?

**Comment by cpuguy83** [comment]
I have asked that the jruby team takes over this image, sadly we have not been able to sync up on this.

Probably if you want to have a java11 based image, please make a pull request to add the new imagehere and then we can update the jruby build manifest.

**Comment by LizhangX** [comment]
Thank you again!
I will definitely see what I can work with that.
