### ISSUE TITLE
Install git in jruby:1.7.18-onbuild image

### ISSUE THREAD

**Issue by cap10morgan** [jruby/docker-jruby#6]
Due to a bug in jruby 1.7.19 I need to use 1.7.18, but when I try using the jruby:1.7.18-onbuild image, bundle install fails because I have git sources in my Gemfile but git is not installed in the image.

I can't install git in my own Dockerfile because the ONBUILDs have already fired by then and I'd rather not have to introduce an intermediate image just for this.

**Comment by cap10morgan** [comment]
Looks like this has already been corrected upstream. Just building and pushing a new jruby:1.7.18-onbuild image would fix it.

**Comment by cap10morgan** [comment]
Actually the bug appears to be unrelated to the JRuby version. But still, the 1.7.18-onbuild image should probably have git installed.

**Comment by cpuguy83** [comment]
1.7.19-onbuild image should have git installed already.

**Comment by cap10morgan** [comment]
@cpuguy83 Yep, that's why this issue was about the 1.7.18-onbuild image.

**Comment by cpuguy83** [comment]
I'm sorry, but 1.7.18 is not supported anymore (and isn't in the build manifest for the jruby image either).
If you need 1.7.18 the Dockerfile itself is pretty simple, you could modify it... or not use the onbuild image.
