### ISSUE TITLE
9.2.10.0 build

### ISSUE THREAD

**Issue by HarlemSquirrel** [jruby/docker-jruby#60]
I'm eager to put 9.2.10.0 through some testing on CircleCI but I need this image updated. I'd be happy to help if I can! 😊

**Comment by cpuguy83** [comment]
This was merged a few days ago.Probably the manifest in https://github.com/docker-library/official-images needs to be updated.

**Comment by cpuguy83** [comment]
Opened the PR here: https://github.com/docker-library/official-images/pull/7535

**Comment by cpuguy83** [comment]
Merged.
