### ISSUE TITLE
Latest release tag

### ISSUE THREAD

**Issue by albertogg** [jruby/docker-jruby#68]
Hi @cpuguy83, now that issues are resolved, can you please push the latest tag to the Docker HUB.

Thanks!

**Comment by cpuguy83** [comment]
If you want you can open a PR to github.com/docker-library/official-images and update the library/jruby file to point at the new commit.

I am curious if this will break anyone, though.
@tianon 

re: #67 - Re-sync bundle config with official ruby image.

**Comment by tianon** [comment]
It might, but I think it should be for the better (see https://github.com/docker-library/ruby/pull/306#issuecomment-572047262 and following discussion).

**Comment by albertogg** [comment]
We can close this as it was resolved!
