### ISSUE TITLE
Additional Images with various JDK versions

### ISSUE THREAD

**Issue by tedt10e** [jruby/docker-jruby#73]
Refer to the discussion from the https://github.com/jruby/jruby/issues/5598#issuecomment-832152808

At this moment, we have JRuby images with OpenJDK jre8, jdk8, jre11, and jdk11.

To discuss adding more images based on other versions of JDK (i.e., jdk15, jdk16, jdk17 of OpenJDK, AdoptOpenJDk, etc.).

Thanks 🙏

**Comment by headius** [comment]
I guess the open question for me is why we wouldn't just have images for all supported releases of Java, which would be everything from 8 to 16 (or 17 this fall). Whether or not Oracle supports a given version is not entirely relevant, since other organizations have stepped up to support the non-LTS versions.

So... @cpuguy83 is there any reason not to just permute all supported JDKs with at least JRuby 9.2.x in the docker images?

**Comment by headius** [comment]
One point of reference, Gradle appears to support 8, 11, and 16. I suspect that is because 8 is still everywhere, 11 is LTS, and 16 is current. That might become 8, 11, and 17 this fall, dropping 16, but I am not sure of their policy.

https://hub.docker.com/_/gradle

**Comment by cpuguy83** [comment]
Only reason to not do a version is

1. Do you want to support it
2. Is the upstream image still being updated

For 2, as long as the version of the image is listed in the build manifest in https://github.com/docker-library/official-images/tree/master/library (e.g. see the list for adoptopenjdk https://github.com/docker-library/official-images/blob/master/library/adoptopenjdk), it gets base image updates.

**Comment by headius** [comment]
Given what @cpuguy83 said I think adding support for Java 16 is appropriate. We will add 17 this fall when it is released, and drop 16 when it is no longer being updated.

**Comment by headius** [comment]
https://github.com/docker-library/official-images/pull/10183

**Comment by headius** [comment]
@tedhexaflow JDK16 will be supported after https://github.com/docker-library/official-images/pull/10183 is merged. Is this good enough for you?

**Comment by headius** [comment]
According to https://github.com/docker-library/official-images/blob/master/library/adoptopenjdk, 15 is also still getting updates, but Oracle has dropped support. I would rather just go with 16 if that is sufficient, and then this fall we will have 17 as LTS.

**Comment by headius** [comment]
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by headius** [comment]
JDK16 support has been merged into official-images.

**Comment by tedt10e** [comment]
Thank you so much 🙏🙏 @headius 

This is good enough.
