### ISSUE TITLE
JRuby with JRE 17

### ISSUE THREAD

**Issue by nfrankel** [jruby/docker-jruby#83]
Hello,

Is there a particular reason why there's no jruby:9.4 with JRE 17?

If not, I'll be happy to provide a PR.

**Comment by headius** [comment]
JRE has largely been deprecated now, hasn't it? We certainly could add it, but I was under the impression that there was no JRE anymore and everyone just ships the full JDK.

**Comment by nfrankel** [comment]
Don't take it wrongly but I don't know what gave you this impression.

Not only is a JDK's image larger than a JRE's, but its attack surface is also larger because of it. In particular, it contains a compiler (that's the idea) and that's a huge security risk in production IMHO.

**Comment by headius** [comment]
I think I got the impression because some shops supporting JDK stopped building JREs, but I have no issues with adding JRE modes for all of the images we push. PR would be great!

**Comment by nfrankel** [comment]
Thanks for the explanation.

Here's the PR: https://github.com/jruby/docker-jruby/pull/84
